packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@icons-pack/react-simple-icons': ^13.8.0
    '@react-router/dev': 7.13.0
    '@react-router/node': 7.13.0
    '@react-router/serve': 7.13.0
    '@supabase/ssr': ^0.8.0
    '@supabase/supabase-js': ^2.94.1
    '@tailwindcss/vite': ^4.1.18
    '@types/luxon': ^3.7.1
    '@types/react': ^19.2.11
    '@types/react-dom': ^19.2.3
    dotenv-cli: ^11.0.0
    isbot: ^5.1.34
    luxon: ^3.7.2
    react: ^19.2.4
    react-dom: ^19.2.4
    react-router: 7.13.0
    supabase: ^2.75.3
    vite: ^7.3.1
    vite-tsconfig-paths: ^6.0.5
    zod: ^4.3.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - supabase
