import fs from "node:fs";
import path from "node:path";
import { mergeConfig, type Plugin, type UserConfig } from "vite";
import { lvhMePlugin } from "./lvh-plugin.ts";

function appNameTypeGenPlugin(appName: string): Plugin {
  return {
    name: "ryugibo:app-name-type-gen",
    configResolved(config) {
      const dtsContent = `// This file is automatically generated by @ryugibo/vite-config.
// Do not edit this file directly.
/// <reference types="vite/client" />

declare const __APP_NAME__: ${JSON.stringify(appName)};
`;
      const typeDir = path.resolve(config.root, ".ryugibo/types");
      if (!fs.existsSync(typeDir)) {
        fs.mkdirSync(typeDir, { recursive: true });
      }
      const targetPath = path.resolve(typeDir, "+env.d.ts");
      fs.writeFileSync(targetPath, dtsContent, "utf-8");
    },
  };
}

export function getBaseViteConfig(appName: string, overrides: UserConfig = {}): UserConfig {
  const defaultConfig: UserConfig = {
    define: {
      __APP_NAME__: JSON.stringify(appName),
    },
    server: {
      host: "0.0.0.0",
      allowedHosts: [`${appName}.lvh.me`],
    },
    plugins: [lvhMePlugin(appName), appNameTypeGenPlugin(appName)],
  };

  return mergeConfig(defaultConfig, overrides);
}
