import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

export function appNameTypeGenPlugin(appName: string): Plugin {
  return {
    name: "ryugibo:app-name-type-gen",
    configResolved(config) {
      const dtsContent = `// This file is automatically generated by @ryugibo/vite-config.
// Do not edit this file directly.
/// <reference types="vite/client" />

declare const __APP_NAME__: ${JSON.stringify(appName)};
`;
      const typeDir = path.resolve(config.root, ".ryugibo/types");
      if (!fs.existsSync(typeDir)) {
        fs.mkdirSync(typeDir, { recursive: true });
      }
      const targetPath = path.resolve(typeDir, "+env.d.ts");
      fs.writeFileSync(targetPath, dtsContent, "utf-8");
    },
  };
}
